// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceParkAPI.Data.DB;

namespace SpaceParkAPI.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    [Migration("20210503115254_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceParkAPI.Parkingspot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("CharacterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSize")
                        .HasColumnType("int");

                    b.Property<int>("MinSize")
                        .HasColumnType("int");

                    b.Property<string>("SpaceshipName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Parkingspots");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 500,
                            MinSize = 0
                        },
                        new
                        {
                            ID = 2,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 500,
                            MinSize = 0
                        },
                        new
                        {
                            ID = 3,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 500,
                            MinSize = 0
                        },
                        new
                        {
                            ID = 4,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 500,
                            MinSize = 0
                        },
                        new
                        {
                            ID = 5,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 500,
                            MinSize = 0
                        },
                        new
                        {
                            ID = 6,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 5000,
                            MinSize = 500
                        },
                        new
                        {
                            ID = 7,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 5000,
                            MinSize = 500
                        },
                        new
                        {
                            ID = 8,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 5000,
                            MinSize = 500
                        },
                        new
                        {
                            ID = 9,
                            Arrival = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxSize = 120000,
                            MinSize = 5000
                        });
                });

            modelBuilder.Entity("SpaceParkAPI.Receipt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParkingspotID")
                        .HasColumnType("int");

                    b.Property<string>("StarshipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ParkingspotID");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("SpaceParkAPI.Receipt", b =>
                {
                    b.HasOne("SpaceParkAPI.Parkingspot", "Parkingspot")
                        .WithMany()
                        .HasForeignKey("ParkingspotID");

                    b.Navigation("Parkingspot");
                });
#pragma warning restore 612, 618
        }
    }
}
