version: '3.4'

services:
  spaceparkapi:
    image: ${DOCKER_REGISTRY-}spaceparkapi
    build:
      context: .
      dockerfile: SpaceParkAPI/Dockerfile
  spaceparkdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "41434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "verystrong!pass123"
      MSSQL_PID: Express